# Generated by Django 2.2.7 on 2019-11-11 12:42

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite seu nome completo', max_length=40)),
                ('plano', models.CharField(choices=[('Individual', 'Individual'), ('Familiar', 'Familiar')], default='Individual', help_text='Escolha entre os dois tipos de plano acima (apenas serve como referência)', max_length=10)),
                ('email', models.EmailField(help_text='Obrigatório. Adicione um e-mail para que possamos entrar em contato', max_length=254)),
                ('telefone', phone_field.models.PhoneField(help_text='Digite seu telefone, caso utilize ramal, coloque no campo ext.', max_length=31)),
            ],
        ),
    ]
